name: test_project
description: Test Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <3.22.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.1
  bloc: ^7.1.0
  intl: ^0.17.0
  meta: ^1.3.0
  rxdart: ^0.27.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  connectivity_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
